#!/bin/bash
source $GAMEDIR/library/mainlib.sh

if [ $# -lt 1 ];
then
    echo "Drop what?"
    echo "You have:"
    ls $inventory
else 
    # either drop an item and inform the player
    # or complain about not dropping it
    drop $1 && echo "Dropped item $1" \
	    || echo "Don't have item $1"
fi
