#!/bin/bash
set -o nounset
set -o errexit
room=$(dirname $0)/..
area=$room/..
mydir=$area/../..
inventory=$mydir/inventory

if [ $# -lt 1 ];
then
    echo "Get what?"
elif test -e $room/item/$1;
then
    # grab item
    echo "Grabbing item $1"
    mkdir -p $inventory
    mv $room/item/$1 $inventory;
else 
    echo "No item $1 in sight"
fi
