#!/bin/bash
source $GAMEDIR/library/mainlib.sh

if [ $# -lt 1 ];
then
    echo "Get what?";
    echo "You see items:"
    ls $room/item
else
    get $1 && echo "Got item $1" \
    || ( test -e $room/fixture/$1 && echo "Can't take $1" ) \
    || echo "No item $1 in sight"
fi
