#!/bin/bash
source $GAMEDIR/library/mainlib.sh

if [ $# -lt 1 ];
then
    echo "Go where?";
    echo "You see exits to:"
    ls $room/link
else
    # change room and describe it,
    # or just complain about it not existing
    change_room $room/link/$1 && describe_room \
    || echo "$1 ain't no place I ever heard of. They speak English in $1?"
fi
