#!/bin/bash
source $GAMEDIR/library/mainlib.sh

if [ $# -lt 1 ];
then
    describe_room

    brief_describe_things $room/item
    brief_describe_things $room/fixture

    echo "You see exits to:"
    ls $room/link
else
    # either describe one thing, or we can't see anything
    describe $room/item/$1 ||
    describe $room/fixture/$1 ||
    describe $inventory/$1 ||
    echo "You can't see that thing."
fi
