#!/bin/bash
set -o nounset
set -o errexit
mydir=$(dirname $0)/..
room=$mydir/location

if [ $# -lt 1 ];
then
    cat $room/description
elif test -e $room/item/$1;
then
    cat $room/item/$1;
elif test -e $room/fixture/$1;
then
    cat $room/fixture/$1;
fi

if test -e $room/item;
then ls $room/item | while read file; do cat $room/item/$file/description; done
fi
if test -e $room/fixture;
then ls $room/fixture | while read file; do cat $room/fixture/$file/description; done
fi

echo "You see exits to:"
ls -1 $room/link
