#!/bin/bash
source $GAMEDIR/library/mainlib.sh

if [ $# -lt 1 ];
then
    echo "Use what?"
    exit 0
else
    item=$1
    shift

    if test -e $inventory/$item;
    then
	use_item $item && echo "Using item $item" \
		|| echo "Can't use item $item"
    elif test -e $room/fixture/$item;
    then
	use_fixture $item && echo "Using fixture $item" \
		|| echo "Can't use fixture $item"
    elif test -e $room/item/$item;
    then echo "You have to get item $item first"
    else 
	echo "No item $item in sight"
    fi
fi
