#!/bin/bash
mydir=$(dirname $(readlink -f $0))/../..
echo $mydir
waterleft=$(cat ${mydir}/water_remaining)
waterleft=$((waterleft - 1))
echo $waterleft > ${mydir}/water_remaining
echo "There's now only $waterleft units of water in the room"
